In [0]:
import pandas as pd
# Note: keep_default_na=False prevents pandas from turning "NA" (North America)
customers_df = pd.read_csv(
    "/Volumes/workspace/sales/sales/customers.csv",
    keep_default_na=False,
    na_values=[""],   # only treat truly empty cells as missing
)

In [0]:
# Quick look at what we're dealing with
print("Shape:", customers_df.shape)
print(customers_df.dtypes)
print(customers_df.isna().sum())
print("\nDuplicates:", customers_df.duplicated().sum())
print("\nSample of region values:", customers_df["region"].unique())
print("Sample of industry values:", customers_df["industry"].unique())

Shape: (41, 7)
customer_id             int64
customer_name          object
industry               object
region                 object
country                object
payment_terms_days    float64
credit_limit_eur        int64
dtype: object
customer_id           0
customer_name         0
industry              1
region                1
country               1
payment_terms_days    1
credit_limit_eur      0
dtype: int64

Duplicates: 0

Sample of region values: ['EMEA' 'NA' nan 'APAC' 'LATAM']
Sample of industry values: ['Retail Fuel' 'Energy' 'Aviation' 'Logistics' 'Manufacturing' 'Maritime'
 nan 'Beverage']

In [0]:
customers_df

    customer_id              customer_name  ... payment_terms_days credit_limit_eur
0        100001         Lufthansa Cargo AG  ...               30.0          5000000
1        100002        Delta Air Lines Inc  ...               90.0           500000
2        100003   KLM Royal Dutch Airlines  ...               60.0           100000
3        100004              Air France SA  ...               30.0           250000
4        100005        British Airways Plc  ...               45.0           250000
5        100006            Maersk Line A/S  ...               45.0          1000000
6        100007              CMA CGM Group  ...               90.0          2500000
7        100008             Hapag-Lloyd AG  ...               60.0           500000
8        100009  Mediterranean Shipping Co  ...               60.0      € 2,500,000
9        100010               DHL Aviation  ...               45.0          1000000
10       100011              FedEx Express  ...               45.0          2500000
11       100012               UPS Airlines  ...               90.0          1000000
12       100013             Shell Aviation  ...               45.0          5000000
13       100014                BP Aviation  ...               30.0          2500000
14       100015     TotalEnergies Aviation  ...               30.0          2500000
15       100016      ExxonMobil Aviation    ...               30.0           500000
16       100017         Chevron Lubricants  ...               30.0          2500000
17       100018                  Repsol SA  ...               45.0          1000000
18       100019   Singapore Airlines Cargo  ...               30.0          2500000
19       100020       Cathay Pacific Cargo  ...               30.0           500000
20       100021             Qantas Freight  ...               30.0           500000
21       100022          Emirates SkyCargo  ...               30.0          5000000
22       100023               Etihad Cargo  ...               60.0        1,000,000
23       100024                  ANA Cargo  ...               60.0           250000
24       100025                LATAM Cargo  ...               45.0           250000
25       100026               LATAM Cargo   ...               90.0          2500000
26       100027           Aeromexico Cargo  ...               45.0          5000000
27       100028               Volvo Trucks  ...               90.0           100000
28       100029                  Scania AB  ...               60.0          2500000
29       100030           Daimler Truck AG  ...               45.0          5000000
30       100031             Stora Enso Oyj  ...               30.0          1000000
31       100032            UPM-Kymmene Oyj  ...               30.0          1000000
32       100033              Wartsila Corp  ...               45.0          1000000
33       100034           Neste Oil Retail  ...                NaN          1000000
34       100035                   Preem AB  ...               45.0          1000000
35       100036                     OMV AG  ...               30.0          5000000
36       100037                Heineken NV  ...               45.0          5000000
37       100038            Carlsberg Group  ...               30.0           500000
38       100039      Coca-Cola Europacific  ...               90.0           250000
39       100040              ArcelorMittal  ...               60.0          1000000
40       100041            Thyssenkrupp AG  ...               60.0           100000
41       100011              FedEx Express  ...               45.0          2500000

[42 rows x 7 columns]

In [0]:
customers_df["region"].unique()

array(['EMEA', 'NA', nan, 'APAC', 'LATAM'], dtype=object)

In [0]:
# --- Clean customer_name
customers_df["customer_name"] = customers_df["customer_name"].str.strip()

In [0]:
customers_df["customer_name"]

0            Lufthansa Cargo AG
1           Delta Air Lines Inc
2      KLM Royal Dutch Airlines
3                 Air France SA
4           British Airways Plc
5               Maersk Line A/S
6                 CMA CGM Group
7                Hapag-Lloyd AG
8     Mediterranean Shipping Co
9                  DHL Aviation
10                FedEx Express
11                 UPS Airlines
12               Shell Aviation
13                  BP Aviation
14       TotalEnergies Aviation
15          ExxonMobil Aviation
16           Chevron Lubricants
17                    Repsol SA
18     Singapore Airlines Cargo
19         Cathay Pacific Cargo
20               Qantas Freight
21            Emirates SkyCargo
22                 Etihad Cargo
23                    ANA Cargo
24                  LATAM Cargo
25                  LATAM Cargo
26             Aeromexico Cargo
27                 Volvo Trucks
28                    Scania AB
29             Daimler Truck AG
30               Stora Enso Oyj
31              UPM-Kymmene Oyj
32                Wartsila Corp
33             Neste Oil Retail
34                     Preem AB
35                       OMV AG
36                  Heineken NV
37              Carlsberg Group
38        Coca-Cola Europacific
39                ArcelorMittal
40              Thyssenkrupp AG
41                FedEx Express
Name: customer_name, dtype: object

In [0]:
# --- Clean industry
customers_df["industry"] = customers_df["industry"].str.strip().str.title()

In [0]:
customers_df["industry"].unique()

array(['Retail Fuel', 'Energy', 'Aviation', 'Logistics', 'Manufacturing',
       'Maritime', nan, 'Beverage'], dtype=object)

In [0]:
# --- Clean credit_limit_eur
customers_df["credit_limit_eur"] = pd.to_numeric(
    customers_df["credit_limit_eur"]
        .astype(str)
        .str.replace("€", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip(),
    errors="coerce",
)

In [0]:
customers_df["credit_limit_eur"]

0     5000000
1      500000
2      100000
3      250000
4      250000
5     1000000
6     2500000
7      500000
8     2500000
9     1000000
10    2500000
11    1000000
12    5000000
13    2500000
14    2500000
15     500000
16    2500000
17    1000000
18    2500000
19     500000
20     500000
21    5000000
22    1000000
23     250000
24     250000
25    2500000
26    5000000
27     100000
28    2500000
29    5000000
30    1000000
31    1000000
32    1000000
33    1000000
34    1000000
35    5000000
36    5000000
37     500000
38     250000
39    1000000
40     100000
41    2500000
Name: credit_limit_eur, dtype: int64

In [0]:
# --- Clean payment_terms_days
customers_df["payment_terms_days"] = pd.to_numeric(
    customers_df["payment_terms_days"], errors="coerce"
)

In [0]:
customers_df["payment_terms_days"]

0     30.0
1     90.0
2     60.0
3     30.0
4     45.0
5     45.0
6     90.0
7     60.0
8     60.0
9     45.0
10    45.0
11    90.0
12    45.0
13    30.0
14    30.0
15    30.0
16    30.0
17    45.0
18    30.0
19    30.0
20    30.0
21    30.0
22    60.0
23    60.0
24    45.0
25    90.0
26    45.0
27    90.0
28    60.0
29    45.0
30    30.0
31    30.0
32    45.0
33     NaN
34    45.0
35    30.0
36    45.0
37    30.0
38    90.0
39    60.0
40    60.0
41    45.0
Name: payment_terms_days, dtype: float64

In [0]:
# --- Drop duplicate rows 
before = len(customers_df)
customers_df = customers_df.drop_duplicates().reset_index(drop=True)
print(f"\nRemoved {before - len(customers_df)} duplicate row(s)")

Removed 1 duplicate row(s)

In [0]:
# --- Final check ---
customers_df.shape

(41, 7)

In [0]:
customers_df.isna().sum()

customer_id           0
customer_name         0
industry              1
region                1
country               1
payment_terms_days    1
credit_limit_eur      0
dtype: int64

In [0]:
customers_df.head()

   customer_id             customer_name  ... payment_terms_days credit_limit_eur
0       100001        Lufthansa Cargo AG  ...               30.0          5000000
1       100002       Delta Air Lines Inc  ...               90.0           500000
2       100003  KLM Royal Dutch Airlines  ...               60.0           100000
3       100004             Air France SA  ...               30.0           250000
4       100005       British Airways Plc  ...               45.0           250000

[5 rows x 7 columns]

In [0]:
# --- Load data into SQL table
(spark.createDataFrame(customers_df)
    .write
    .mode("overwrite")
    .saveAsTable("workspace.sales.customers_2024"))

In [0]:
%sql
Select *
From workspace.sales.customers_2024
Limit 10

customer_id,customer_name,industry,region,country,payment_terms_days,credit_limit_eur
100001,Lufthansa Cargo AG,Retail Fuel,EMEA,United Kingdom,30.0,5000000
100002,Delta Air Lines Inc,Energy,NA,Canada,90.0,500000
100003,KLM Royal Dutch Airlines,Aviation,EMEA,Sweden,60.0,100000
100004,Air France SA,Retail Fuel,EMEA,Netherlands,30.0,250000
100005,British Airways Plc,Logistics,EMEA,UAE,45.0,250000
100006,Maersk Line A/S,Manufacturing,EMEA,United Kingdom,45.0,1000000
100007,CMA CGM Group,Manufacturing,EMEA,Spain,90.0,2500000
100008,Hapag-Lloyd AG,Retail Fuel,null,null,60.0,500000
100009,Mediterranean Shipping Co,Maritime,EMEA,Sweden,60.0,2500000
100010,DHL Aviation,Logistics,EMEA,Spain,45.0,1000000